---
#
# Learn more about this Gitpod configuration file in the documentation at https://www.gitpod.io/docs/configuration
#
ports:
  - port: 3000
    onOpen: open-browser

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks
tasks:
  - name: "SvelteKit Example"
    init: |
      cd sveltekit
      npm install
      npm run dev
    command: |
      export HMR_HOST=`gp url 3000`

vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
