# https://github.com/yuang01/hexo-theme-bamboo
# https://yuang01.gitee.io/2021/02/08/hexo-theme-bamboo-new/#%E6%96%87%E7%AB%A0%20Front-matter%20%E4%BB%8B%E7%BB%8D

menu:
  Archives:
    url: /archive/
    icon: fa fa-archive
  Tags:
    url: /tags/
    icon: fa fa-tags
  Categories:
    url: /categories/
    icon: fa fa-bookmark
  About:
    url: //richiebartlett.com/about.html
    icon: fa fa-user
    children:
    - name: Work
      url: //richiebartlett.com/work.html
      icon: fa fa-building
    - name: Play
      url: //richiebartlett.com/play.html
      icon: fa fa-gamepad
  Statistics:
    url: /statistics/
    icon: fa fa-bar-chart

logo: false # 为空则不显示
favicon: /favicon.ico # or .png .jpg .svg .gif .jpeg .ico
guestIcon: /img/RichieUserICON.svg
preloader:
  on: false

# 首页轮播图设置
swiper:
  # 当在.md文件中，设置swiper:true，会将该文章放到轮播中，
  showPrevNext: true # 是否显示左右切换按钮
  showIndicators: true  # 是否显示指示器
  autoplay: false # 是否自动轮播
  loop: true # 让轮播看起来是循环的, 例如false的话，到达最后一个轮播图的时候，右按钮不能点击
  delay: 5000 # 切换延迟时间
  effect: 'slide' # 'fade': 淡入淡出效果
  textAnimated: 'fadeInDown' # 文字动画，属性使用 animate.css, https://daneden.github.io/animate.css/
  textDuration: '0.2s' # 文字动画持续时间（单位秒）
  textDelay: '0.15s' # 文字动画延迟时间（单位秒）
  readMoreBtn: true # 阅读更多按钮是否显示
  readMoreBtnBackgroundColor: '' # 阅读更多按钮背景颜色,空字符串则默认使用主题颜色
  bubble: false # 轮播图是否显示气泡,也可以打开底下的花瓣或者雪花特效 sakura（花瓣）: true snow(雪花): true
  # 当没有文章设置swiper: true时候，轮播图会显示以下default默认内容，可自行切换对应内容
  defaultImg: '/img/Tokyo_Tours.jpeg' # 图片，没有则随机选取
  defaultTile: "What's on Richie's mind" # 标题
  defaultDesc: ['Father', 'Entrepreneur', 'Platform Architect', 'Blockchain developer', 'Adventurer', 'Philosopher', 'Academic', 'Adult Fan of LEGO']
  defaultMoreLink: '/2021/0527/Fun_楽しい物/Designing-a-new-Blog-for-RichieBartlett-com.html' # 阅读更多链接 
  defaultBtnText: 'RichieBartlett.com 2022' # 阅读更多右边的按钮的文字
  defaultBtnLink: '/2021/0527/Fun_楽しい物/Redesigning-RichieBartlett-com.html' # 阅读更多右边的按钮的链接
  defaultDescTyped: true # defaultDesc文字是否开启打字特效
  defaultDescTypedLoop: true # defaultDesc文字的打字特效是否循环
  # defaultAddToSwiper表示：当有文章设置了swiper: true的时候，将上面的 默认内容 放在轮播图的第一页
  defaultAddToSwiper: true # 开启这个，则loop默认为false
  ## 轮播图样式更改
  # 轮播图的文字和按钮居中显示 (针对 imgwidthFull和 full都是false的时候)
  textCenter: true
  # 图片宽度为100% (轮播图的文字和按钮只能居中显示)
  imgwidthFull: false
  # 整个轮播图宽高都是100%  (轮播图的文字和按钮只能居中显示)
  full: true # full 优先级大于 imgwidthFull

# Show up arrow when scrolling down page (returns user to top)
goTop: 
  on: true

# 图片点击放大功能
fancybox: 
  on: true

# site-hit counter
busuanzi:
  on: true
# 标签页和分类页中，显示这个标签或者分类在文章中出现的次数
show_count: true

# 打赏功能
donate:
  on: true
donate_message: Coffee change helps a lot
# 支付宝打赏图片相对路径
# Alipay: '/img/zfb.jpg'
# 微信打赏图片相对路径
# WeChatpay: '/img/wx.jpg'

# 分享功能
sharejs: 
  on: false
  sites: twitter,facebook,google,qq,qzone,wechat,weibo,douban,linkedin

# Social Manager service
addThis: 
  on: true
  admin: https://www.addthis.com/dashboard#gallery/pub/ra-4f7378e432ba4797
  pubID: ra-4f7378e432ba4797

# 鼠标点击特效
cursor_effect:
  on: false
  type: text  # fireworks: 礼花 | explosion: 爆炸 | love: 浮出爱心 | text: 浮出文字

# 头部导航是否显示天气
weather:
  on: false

# 全文搜索功能
search:
  on: true

# 文章详情页底部显示上一篇文章和下一篇文章
postNav:
  on: true

# 复制成功提示
copy:
  on: true
  title: 'Clipboard'
  content: 'Copied'

# 文章详情页的标题是否显示在顶部图片中, false则显示在文章内容顶部
postTitleTop:
  on: true

# 输入框打字特效
inputEffects:
  on: true

## background "ribbon" that changes on every click
ribbon:
  on: false

# live-2d(左下角动画人物)
live2d:
  on: false # 控制显示或者隐藏
  modelId:  # 0 or 1 or 2 or 3 or 4 or 5 or 6
  open: true # 默认展开，false则收缩，通过点左下角的方块点击，控制展开或者收缩

# 首页雪花飘落效果--冬天
snow:
  on: false
  onlyPc: true # 设为true，只有pc端显示雪花特效

# 首页花瓣飘落效果--春天
sakura:
  on: false
  onlyPc: false # 设为true，只有pc端显示花瓣特效

# 首页文章图片是否一左一右交错显示
homePostImgsPosition:
  on: true
  left: true # 当上面的on设置为false（不交叉显示），则指定left为true的时候，图片在左边显示

# 灯笼
lantern: ## great for Chinese NEW YEAR
  on: false
  left: '令和' # 左边灯笼的文字， 空字符串则没有文字
  right: '5' # 右边灯笼的文字

# 首页文章列表滚动动画，详情参照https://github.com/michalsnik
aos:
  on: true
  animate: 'fade-up' # animate, 更多选项请参考 https://github.com/michalsnik/aos#animations
  offset: 120 # offset (in px) from the original trigger point
  delay: 0 # values from 0 to 3000, with step 50ms
  duration: 400 # values from 0 to 3000, with step 50ms
  easing: 'ease' # default easing for AOS animations
  once: true # whether animation should happen only once - while scrolling down
  mirror: false # whether elements should animate out while scrolling past them
  anchorPlacement: 'top-bottom' # defines which position of the element regarding to window should trigger the animation

# 添加 Google Analytics 配置
googleAnalytics:
  on: false
  id: GTM-5P93L9N

# 添加 baidu Analytics 配置
baiduAnalytics:
  on: false
  id:

# 百度搜索资源平台提交链接
baiduPush: false

# 文章目录
toc:
  on: true # 是否显示
  heading: h2, h3, h4, h5, h6
  open: true # 是否展开，false则收缩

# 音乐
# 是否在首页显示音乐.
music:
  on: false
  autoHide: true    # hide automaticaly
  server: netease   #require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    #require song, playlist, album, search, artist
  id: 442274724     #require	song id / playlist id / album id / search keyword
  fixed: true       # 开启吸底模式，建议开启
  autoplay: false   # 是否自动播放
  theme: '#42b983'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true  # 列表默认折叠
  hideLrc: true     # 隐藏歌词

# 关于我
baseInfo:
  on: true
  age: 43 # 年龄
  sex: '男' # 性别
  coordinate: 'Scorpio' # 坐标
  status: 'Always busy' # 状态

#版权信息  coryRyght
copyright:
  on: true

# 首页座右铭
motto:
  on: false
  title: '座右铭'
  content: '沉淀后我愿意做个温暖的人，有自己的喜好，有自己的原则，有自己的信仰，不急功近利，不浮夸轻薄。宠辱不惊，淡定安逸，心静如水，不忘初心，方得始终。——凌茜'
  background: 'url("https://img10.360buyimg.com/ddimg/jfs/t1/166587/8/21344/72069/6088c24fEda5fdeb6/f9730ab637b7ca47.png")' # url("xxx") or red or #000 or rgba() ..

# 首页公告
notice:
  on: false
  seamless: false # 为true时，则无缝不停止滚动，false是会停一下的滚动
  title: '公告'
  background: 'url("https://img10.360buyimg.com/ddimg/jfs/t1/166587/8/21344/72069/6088c24fEda5fdeb6/f9730ab637b7ca47.png")' # url("xxx") or red or #000 or rgba() ..
  list: # list相当于数组对象，[{title:'xx',date: 'xx', url: 'xxx', color: 'red'}]根据自己实际情况，增加或者删除
    - title: '#博客更新到2.0了'
      date: '2021-04-28'
      url: '/archives'   # 可以为空, 也可以是本地页面地址如 '/archives'
      color: red   # 字体颜色
    - title: '#新增 归档，分类等页面头部图片位置可以设置为视频 ~'
      date: '2021-04-28'
      url: 'http://baidu.com'
      color: '#42b983'
    
  

# 文章置顶
topArticle: ## Recommended Article section
  on: true
  background: 'rgba(255,255,255,1)' # url("http://xxx.png") or red or #000 or rgba() ..

# 文章详情页图片上的标题打字效果
typed:
  on: true
  loop: false # 是否循环
  showCursor: true # 是否显示光标
  startDelay: 90 # 开始延迟
  typeSpeed: 70 # 打字速度
  backSpeed: 40 # 删除速度

# 文章详情页图片上的气泡效果
bubble:
  on: false

## Third party comments managing service
disqus:
  on: true
  user: lorezyra

# valine 评论
valine:
  on: false
  appid: 
  appkey: 
  avatar: '' # 匿名者头像选项 https://valine.js.org/avatar.html
  placeholder: '客官，说点什么吧' # 评论内容输入框的 placeholder
  master: '' # 博主标签识别，博主邮箱md5 可以去md5加密网站，例如 https://md5jiami.51240.com/ ，将自己的邮箱输入， 得到 32位小写 的字符串
  friends: [] # 小伙伴的 邮箱md5， 是个数组
  requiredFields: ['nick', 'mail'] # 设置必填项 ['nick', 'mail'] nick为昵称必填， mail为邮箱必填，建议设置必填，填写qq邮箱，会使用qq头像作为头像
  backgroundImg: '/img/comment-bg.gif' # 右下角背景图片
  backgroundColor: 'rgba(255,255,255,0.9)' # 背景颜色

# twikoo评论
# https://twikoo.js.org
twikoo:
  on: false
  envId: twikoo-1gs9l0fb17e7897a # 环境 ID，搭建教程：https://twikoo.js.org/quick-start.html
  # region: ap-guangzhou # 环境地域，默认为 ap-shanghai
  # path: 'window.location.pathname' # 自定义文章路径

# miniValine
miniValine:
  on: false
  appid: 
  appkey: 
  avatar: '' # 匿名者头像选项 https://valine.js.org/avatar.html
  placeholder: '客官，说点什么吧'

# 来必力评论
livere:
  on: false
  livere_uid:

# gitment 评论
gitment:
  on: false
  gitment_owner:       #你的 GitHub ID
  gitment_repo: #存储评论的 repo
  clientId: #client ID
  clientSecret:       #client secret

# 畅言评论
changyan:
  on: false
  appId:
  conf:

# gitalk评论
gitalk:
  on: false         # 用来做启用判断可以不用
  owner:        #Github 用户名,
  repo:        #储存评论issue的github仓库名
  admin:        #Github 用户名,
  clientID:      #`Github Application clientID`
  clientSecret:  #`Github Application clientSecret`

# 弹幕 只对valine评论有效
danmu:
  on: false
  loop: false # 设为true，则弹幕完了之后，继续查询评论接口，将该篇文章的评论再显示在弹幕里
  delay: 5000 # 每条弹幕之间出现的间隔时间
  speed: 20 # 弹幕运行的速度, 越小越快

# 归档页面图片、描述、视频，全屏 or 'http://xxx'
archive:
  title: 'archive'
  img: '/img/library.svg'
  desc: 'Seek the past and maybe understand the future'
  full: true # 设置为true，则图片全屏显示
  video: '' # If defined, will play video (920px) instead of displaying static img.

# 标签页面，配置同上
tag:
  title: 'tags'
  img: '/img/hashTags.svg'
  desc: 'Find your topic and be found interested'
  full: true # 
  video: '' 

# 标签详情页面，配置同上
tagDetail:
  title: 'tag'
  img: '/img/hashTags.svg'
  desc: 'Found an interesting topic?'
  full: false
  video: ''

# 分类页面，配置同上
categories:
  title: 'categories'
  img: '/img/categories.svg'
  desc: 'My interests are varied, hence many categories'
  full: true
  video: ''

#分类详情页面，配置同上
categoryDetail:
  title: 'category'
  img: '/img/categories.svg'
  desc: 'Another curious category'
  full: false
  video: ''


# 黑夜模式, 关灯
dark:
  on: true # 是否在头部导航上显示开关灯
  default: false  # true为默认关灯状态（刷新页面和跳转页面都是关灯状态），false为默认开灯状态(网页第一次打开的时候为开灯状态)

# 主题颜色
color_scheme:
  # ------------
  # 通用颜色
  common:
    # 主题色
    theme: '#FA6800'
    # 主题色块内部的文字颜色
    inner: '#FBFAF5' #FDF4DC
    # 链接色 a标签
    link: '#736AAD' #2805FC #B88765
    # border颜色，目前轮播图的 阅读更多按钮 和 回到顶部按钮 有用到该border，可自行配置该颜色
    border: '2px solid #42b983'
    # 选中区域文字的背景颜色, 后面的小数代表透明度
    selection: 'alpha(#42b983, 0.8)'
    # 顶部页面加载进度条颜色
    pace: '#f6a427'
    # 滚动条颜色, 空字符串则滚动条使用 主题色，否则强制使用该颜色
    scroll: '#B88765'
    # 首页文章列表的背景颜色, url("http://xxx.png") or red or #000 or rgba() ..
    postListBackground: 'rgba(255,255,255,1)'
    # 首页页面的底部背景颜色，空字符串透明('transparent')，可以是白色('#fff')等颜色, 也可以是图片，例如  'url("https://img11.360buyimg.com/ddimg/jfs/t1/169624/29/16/4603017/5fec2c79Eecbd536a/308b28b82a013cd2.png")'
    bgFloor: 'url("")' # 如果是图片地址，url里面请用双引号
    # 头部导航是否背景透明，滚动条在对顶端的时候,头部导航背景透明
    headerMenuTransparent: true
    headerMenuBackgroundColor: '' # 头部导航背景颜色, 为空则使用主题色, 写法: alpha(#42b983, 0.8) or rgba(268, 264, 269, 0.8) or #42b983 or red
  # 文章详情页 颜色属性
  post:
    # 文章详情页面-->标题在图片上时候的颜色
    headerTitle: '#FDF4DC'
    # 文章详情页面-->标题在图片上时候字体粗细
    headerTitleFontWeight: 'normal' # 100-900 or bold, normal, bolder, lighter
    #文章详情页面--> copy按钮背景色, 空字符串则copy按钮背景为 主题颜色，否则强制使用该颜色
    copyBackground: ''
    #文章详情页面--> copy按钮文字颜色, 空字符串则copy按钮字体颜色为 主题色块内部的文字颜色，否则强制使用该颜色
    copyColor: ''
    # 代码高亮部分的背景色, 空字符串则使用-代码高亮配置-的背景颜色，否则强制使用该颜色作为代码高亮背景色
    codeBackground: ''
    # 文章详情页面--> p标签使用 ``符号 突出的文字颜色
    pLight: '#d63200'
    # 文章详情-页面-> p标签颜色
    p: '#273849'
    # 文章详情页面--> title颜色， h1, h2, h3..
    title: '#273849'
    # 文章详情页面 -->右侧目录文字颜色
    toc: '#273849'
    # 文章详情页面 --> font-family
    fontFamily: '-apple-system,BlinkMacSystemFont,PingFang SC,Segoe UI,Microsoft YaHei,Hiragino Sans GB,Helvetica Neue,Helvetica,Arial,sans-serif'
    # 文章详情页面 --> 透明度, 左侧文章内容背景颜色的透明度
    contentOpacity: '1'
    # 文章详情页面 --> 透明度, 右侧文章目录背景颜色的透明度
    tocOpacity: '0.8'
    # bgImg -- 文章详情页背景图, 针对所有的文章详情页背景
    # 可以是数组（数组里面是图片地址，多个图片地址会采用 幻灯片 循环显示），
    # 如果背景只想要一个图片：可以使用 ['http://xxxxxx'] 或者 'http://xxxxxxx'，这样的写法, 图片地址也可以是本地路径('/img/xxx.png' or '/img/xxx.png')
    # 也可以是颜色字符串（例如'#C7EDCC', 或者rgba(0 ,0 ,0, 0.8) 那么会使用该颜色作为背景）
    # 空字符串则背景颜色为透明
    bgImg: [ 
      ""
    ]
    # 背景图幻灯片模式--延迟时间
    # 如果bgImg设置为数组，数组里面是多个图片地址,则 bgImgDelay表示背景图幻灯片的 延迟间隔时间
    bgImgDelay: 180000 # 默认三分钟，切换一张图片
    # 如果bgImg设置为数组，数组里面是多个图片地址,则 bgImgTransition表示背景图幻灯片的 动画效果
    bgImgTransition: 'fade' # fade, scale, translate-fade,
    ## bgImg，bgImgDelay，bgImgTransition三个属性除了可以在这里全局配置，还可以在单独的文章里配置
    ## 单独的文章里配置，则这bgImg，bgImgDelay，bgImgTransition三个属性优先使用单独的文章里配置的


# tag标签 按钮，文本高亮等等..
tag_plugins:
  # 所有标签用到的颜色值，可自行修改
  warningColor: '#e6a23c'
  dangerColor: '#f66'
  successColor: '#67c23a'
  infoColor: '#409eff'
  yellow: '#f9ed69'
  red: '#f47983'
  green: '#16a951'
  blue: '#177cb0'
  cyan: '#00e09e'
  # link标签的左侧默认图片
  linkImg: '/img/AdobeStock_86171113.svg'


# 鼠标手势
# cursor:
#   pointer: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/pointer.png
#   default: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/left_ptr.png
#   text: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/text.png

# loading图片地址，为空则不使用loading图片，文章详情页的loading图片可从`postLoadingImg`参数控制
loadingImg: '/img/circularLOAD.gif'
# 文章详情页的loading图片地址，为空则不使用loading图片
postLoadingImg: '/img/jelly-fluid-loader.gif'

# prismjs 代码高亮，在根目录下的_config.yml文件中将prismjs.enable设为true的时候, 在这里选择主题样式
prismjs:
  theme: 'dark' # default, coy, dark, funky, okaidia, solarizedlight, tomorrow, twilight

# highlight代码高亮，在根目录下的_config.yml文件中将highlight设为true的时候，在这里自定义颜色值
# https://github.com/chriskempson/tomorrow-theme
highlight:
  background: '#2d2d2d'
  currentLine: '#393939'
  selection: '#515151'
  foreground: '#cccccc'
  comment: '#999999'
  red: '#f2777a'
  orange: '#f99157'
  yellow: '#ffcc66'
  green: '#99cc99'
  aqua: '#66cccc'
  blue: '#6699cc'
  purple: '#cc99cc'

# 文章图片
imgs:
- '/img/1.jpg'
- '/img/2.jpg'
- '/img/3.jpg'
- '/img/4.jpg'
- '/img/5.jpg'
- '/img/6.jpg'
- '/img/7.jpg'
- '/img/8.jpg'
- '/img/9.jpg'
- '/img/10.jpg'
- '/img/11.jpg'
- '/img/12.jpg'
- '/img/13.jpg'
- '/img/14.jpg'
- '/img/15.jpg'

CDN:
  copyRight: https://creativecommons.org/licenses/by-nc-nd/4.0/
##  fontAwesome: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/fontawesome.min.css
  valine: /js/valine/Valine.min.js ## https://cdn.jsdelivr.net/gh/HCLonely/Valine@latest/dist/Valine.min.js
  MiniValine: /js/valine/MiniValine.min.js ## https://unpkg.com/minivaline/dist/MiniValine.min.js
  iconfont: /css/font_1911880_c1nvbyezg17.css ## https://at.alicdn.com/t/font_1911880_c1nvbyezg17.css
### https://github.com/DIYgod/APlayer
  aplayer: /js/aplayer/APlayer.min.js  ## https://cdn.bootcdn.net/ajax/libs/aplayer/1.10.1/APlayer.min.js
  Meting: /js/Meting.min.js ## https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js
  livere: /js/livere/embed.dist.js ## https://cdn-city.livere.com/js/embed.dist.js
  gitmentCss: /js/gitment/default.min.css ## https://cdn.bootcdn.net/ajax/libs/gitment/0.0.3/default.min.css
  gitmentJs: /js/gitment/gitment.browser.min.js ## https://cdn.bootcdn.net/ajax/libs/gitment/0.0.3/gitment.browser.min.js
  gitalkCss: /js/gitalk/gitalk.css ## https://cdn.bootcdn.net/ajax/libs/gitalk/1.7.2/gitalk.css
  gitalkJs: /js/gitalk/gitalk.js ## https://cdn.bootcdn.net/ajax/libs/gitalk/1.7.2/gitalk.js
  busuanzi: /js/busuanzi/pure.mini.js ## //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js # 卜算子
  ayuCss: '/js/v-plugs-ayu/ayu.css' ## https://cdn.jsdelivr.net/npm/v-plugs-ayu/lib/ayu.css
  ayuJs: '/js/v-plugs-ayu/ayu.umd.min.js' ## https://cdn.jsdelivr.net/npm/v-plugs-ayu/lib/ayu.umd.min.js
  live2d: /js/live2d/autoload.js ## https://cdn.jsdelivr.net/gh/yuang01/live2d-widget@latest/autoload.js
  paceJs: /js/pace/pace.min.js ## https://cdnjs.cloudflare.com/ajax/libs/pace/1.2.4/pace.min.js
  paceCss: '/js/pace/themes/orange/pace-theme-flash.css' ## https://cdnjs.cloudflare.com/ajax/libs/pace/1.2.4/themes/orange/pace-theme-flash.min.css
  weather: '/js/qweather/he-simple-common.js' ## https://widget.qweather.net/simple/static/js/he-simple-common.js?v=2.0
